// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXVISWm7mC3zLW6dvgZRBbaPgUoAczBk',
    appId: '1:1068566303621:web:2b4d8d35d6fab343d26aec',
    messagingSenderId: '1068566303621',
    projectId: 'activity-monitor-c51db',
    authDomain: 'activity-monitor-c51db.firebaseapp.com',
    storageBucket: 'activity-monitor-c51db.firebasestorage.app',
    measurementId: 'G-6NETCZTCQ3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPXVISWm7mC3zLW6dvgZRBbaPgUoAczBk',
    appId: '1:1068566303621:web:518ec5ba5c9823a1d26aec',
    messagingSenderId: '1068566303621',
    projectId: 'activity-monitor-c51db',
    authDomain: 'activity-monitor-c51db.firebaseapp.com',
    storageBucket: 'activity-monitor-c51db.firebasestorage.app',
    measurementId: 'G-MC4PQ79M7E',
  );
}
